name: login_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.11

  path: ^1.8.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
